spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: favoriteModule
          uri: lb://FAVORITE-SERVICE
          predicates:
            - Path=/favorites/**
        - id: servicePaymentModule
          uri: lb://SERVICING-PAYMENT-SERVICE
          predicates:
            - Path=/service-payment/**
        - id: paymentModule
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/oauth-secure
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080