spring:
  application:
    name: favorite-service
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3308/servicedb
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/oauth-secure
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083