spring:
  application:
    name: favorite-service
  r2dbc:
    url: r2dbc:pool:mysql://${services.url.mysqldb}:3306/servicedb
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${services.url.keycloak}:8080/realms/oauth-secure
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${services.url.eureka}:8761/eureka/
server:
  port: 8083
