spring:
  application:
    name: favorite-service
  r2dbc:
    url: r2dbc:pool:mysql://192.168.1.10:3308/servicedb
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.10:9999/realms/oauth-secure
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://192.168.1.10:8761/eureka/
server:
  port: 8083
