spring:
  application:
    name: payment-service
  redis:
    host: 192.168.1.10
    port: 6380
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.10:9999/realms/oauth-secure
service:
  url:
    api:
      servicePayment: http://192.168.1.10:8080/service-payment
      favorite: http://192.168.1.10:8080/favorites
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://192.168.1.10:8761/eureka/
server:
  port: 8081
