spring:
  application:
    name: payment-service
  redis:
    host: "${services.url.redis-cache}"
    port: 6380
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${services.url.keycloak}:8080/realms/oauth-secure"
service:
  url:
    api:
      servicePayment: "http://${services.url.service-payment}:8082/service-payment"
      favorite: "http://${services.url.favorite}:8083/favorites"
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: "http://${services.url.eureka}:8761/eureka/"
server:
  port: 8081
