spring:
  application:
    name: servicing-payment-service
  data:
    mongodb:
      host: 192.168.1.10
      port: 27016
      database: servicedb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.10:9999/realms/oauth-secure
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.10:8761/eureka/
server:
  port: 8082
