spring:
  application:
    name: servicing-payment-service
  data:
    mongodb:
      host: localhost
      port: 27016
      database: servicedb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/oauth-secure
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082